package hf.generateEntity;

import java.util.Date;

public class AuditionAuthor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.author_id
     *
     * @mbggenerated
     */
    private Long authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.author_name
     *
     * @mbggenerated
     */
    private String authorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.head_photo
     *
     * @mbggenerated
     */
    private String headPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.author_desc
     *
     * @mbggenerated
     */
    private String authorDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.first_letter
     *
     * @mbggenerated
     */
    private String firstLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.first_name
     *
     * @mbggenerated
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.last_name
     *
     * @mbggenerated
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.page_no
     *
     * @mbggenerated
     */
    private Integer pageNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.vote_count
     *
     * @mbggenerated
     */
    private Integer voteCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.creation_time
     *
     * @mbggenerated
     */
    private Date creationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audition_author.last_modified_time
     *
     * @mbggenerated
     */
    private Date lastModifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    public AuditionAuthor(Long authorId, String authorName, String headPhoto, String authorDesc, String firstLetter, String firstName, String lastName, Byte type, Integer pageNo, Integer voteCount, Date creationTime, Date lastModifiedTime) {
        this.authorId = authorId;
        this.authorName = authorName;
        this.headPhoto = headPhoto;
        this.authorDesc = authorDesc;
        this.firstLetter = firstLetter;
        this.firstName = firstName;
        this.lastName = lastName;
        this.type = type;
        this.pageNo = pageNo;
        this.voteCount = voteCount;
        this.creationTime = creationTime;
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.author_id
     *
     * @return the value of audition_author.author_id
     *
     * @mbggenerated
     */
    public Long getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.author_name
     *
     * @return the value of audition_author.author_name
     *
     * @mbggenerated
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.head_photo
     *
     * @return the value of audition_author.head_photo
     *
     * @mbggenerated
     */
    public String getHeadPhoto() {
        return headPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.author_desc
     *
     * @return the value of audition_author.author_desc
     *
     * @mbggenerated
     */
    public String getAuthorDesc() {
        return authorDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.first_letter
     *
     * @return the value of audition_author.first_letter
     *
     * @mbggenerated
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.first_name
     *
     * @return the value of audition_author.first_name
     *
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.last_name
     *
     * @return the value of audition_author.last_name
     *
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.type
     *
     * @return the value of audition_author.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.page_no
     *
     * @return the value of audition_author.page_no
     *
     * @mbggenerated
     */
    public Integer getPageNo() {
        return pageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.vote_count
     *
     * @return the value of audition_author.vote_count
     *
     * @mbggenerated
     */
    public Integer getVoteCount() {
        return voteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.creation_time
     *
     * @return the value of audition_author.creation_time
     *
     * @mbggenerated
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audition_author.last_modified_time
     *
     * @return the value of audition_author.last_modified_time
     *
     * @mbggenerated
     */
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }
}