package hf.generateEntity;


import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AuditionAuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int countByExample(AuditionAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int deleteByExample(AuditionAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long authorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int insert(AuditionAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int insertSelective(AuditionAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    List<AuditionAuthor> selectByExample(AuditionAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    AuditionAuthor selectByPrimaryKey(Long authorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AuditionAuthor record, @Param("example") AuditionAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AuditionAuthor record, @Param("example") AuditionAuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AuditionAuthor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audition_author
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AuditionAuthor record);
}